### ISSUE TITLE
Code reuse with Guess.js

### ISSUE THREAD

**Issue by mgechev** [lukeed/webpack-route-manifest#1]
Hey @lukeed, looking at `webpack-route-manifest`, it seems like there's quite some intersection with `guess-parser`. The `guess-parser` tries to statically find the routes in the application and forms the route map using statistics from Google Analytics or another analytics source.

Currently, Guess.js prefetches only JavaScript modules, but it's on the roadmap to expand it to any static assets used in the individual pages.

The `guess-parser` can discover the chunk-route mapping for Angular apps quite easily, because of the static nature of the route definitions there. For React, we currently rely on a series of conventions, but I believe by applying dynamic analysis, we can cover a broader range of use cases.

I believe there might be a place for collaboration and code reuse across both plugins, specifically around:
- Statically/dynamically finding the routes and their corresponding JavaScript chunks. This seems specifically attractive for collaboration because there's no good static solution for React given the dynamic route declarations there.
- Discovering the assets that each route uses. I see that currently, you're using `bundle.getStats()`.

**Comment by lukeed** [comment]
Hey~! 👋 Thanks for stopping by 😄 

What is it you'd like from me / this repo? Regrettably I'm not _super_ familiar with Guess.js, but yes, it does seem like there's some shared spaced here.

As you probably saw, there's not much to this plugin at all. I can extract things for you, but I don't think that's what you're pitching. 

I intend for this plugin to be wrapped/extended by more opinionated toolkits and frameworks. I maintain a thing called `@pwa/cli`, which has an opinionated set of aliases used for importing. For example, the PWA-wrapped version will auto-classify anything with the `@pages/` prefix as a valid route, and ignore the rest.

I imagine you can employ a similar logic for Angular and CRA apps?

To address what _I think_ you're after, I pushed 07b7b0c which allows one to exclude routes entirely from the manifest. This basically means that the CLI-framework (and/or Google Analytics deductions) can pick and choose what should be classified as a "preloadable" route.

**Comment by mgechev** [comment]
I see that `webpack-route-manifest` relies on the user to provide:

>Map your application's import() statements into the URL route patterns they'll operate on.

This is something that Guess.js tries to automatically figure out by [statically analyzing](https://github.com/guess-js/guess/tree/master/packages/guess-parser) the application.

As I mentioned above, React's route declaration is *very* dynamic, which makes it impossible to figure out this mapping in the general case at build time.

I'm suggesting, that there's probably space for a small library, which performs runtime analysis. It traverses the entire application and figures out the chunks associated with each path (which entry points have been passed to `import()` expressions).

`react-snap` uses similar approach to prerender the app's pages.

**Comment by lukeed** [comment]
The plugin forwards all import paths to the user via the `routes` config, then yes, it's up the user to say "this is X, that is Y, I don't care about ...Z"

My initial pass at this _tried_ to do this work at runtime via the [webpack rutime manifest](https://webpack.js.org/concepts/manifest/#runtime). The problem is that a lot of the crucial information is lost in the runtime format. You can still follow the links and build a map of X-needs-Y (because webpack is doing this, so it _has_ to be possible), but you aren't in a position to figure out `1.abc123.js` was the About page, for example.

This is probably why you're able to bridge that gap in Angular. The "route identification process" is mostly opinionated so you can figure it out. Whereas, as you said, there are 1,000 ways to wire up routing for a React application... so you either need a runtime per routing solution, _or_ let the user do the heavy-lifting of "route identification" ahead of time.

The "runtime" I foresee for this manifest (and am finishing soon) will compare the runtime URLs against the pre-generated route patterns (as determined by the user mapping). This becomes _very_ fast and cheap because the bulk of the work was done earlier... which, IMO, is one of the main benefits of having a build phase in the first place.

**Comment by mgechev** [comment]
I see Guess.js consuming the output of the `webpack-route-manifest` (specifically for React). Since the `GuessPlugin` has the probabilities for the user to need page `Y` after page `X`, if we have a manifest with which resources belong to `Y` we'll be able to prefetch them.

I'll be happy to delegate this part of the logic to a different plugin to reduce maintenance cost.

**Comment by lukeed** [comment]
Ah, cool!

If you cant wait a little bit, I'm releasing that runtime module and perhaps it will suit your needs too. I can resume work on it tonight after work.

_My_ runtime won't actually do the prefetching – it just tells you want should be prefetched for a given URL. I need this exact behavior (and only this) in some other places.
The runtime itself is roughly 400 bytes.

**Comment by mgechev** [comment]
>My runtime won't actually do the prefetching – it just tells you want should be prefetched for a given URL. I need this exact behavior (and only this) in some other places.

That's perfect. Guess.js introduces prefetching instructions in each chunks for the assets that are likely to be needed next.

I can wait, no rush at all. I'll probably find enough time to introduce this in a month or two.

A format similar to the one below would be ideal:

```json
{
  "/blog": [
    "foo.js",
    "bar.png"
  ],
  "/post/:id": [
    "qux.ttf"
  ]
}
```

**Comment by lukeed** [comment]
Perfect!

You get that format when you leave `headers` u configured. By default the manifest is just a list of file paths per route. They remain as objects but it's a quick loop to pull out the `hrefs`: https://github.com/lukeed/webpack-route-manifest/blob/master/test/index.js#L165

**Comment by mgechev** [comment]
Thanks for sharing it! I'm traveling as well and after that I have even more travels. Chances are I won't have the bandwidth until the end of November/December.

Closing the issue here :)

**Comment by lukeed** [comment]
Sounds good, enjoy :)

Ping me wherever you pick this up, I'd be happy to chip in as there's definitely overlap here
