### ISSUE TITLE
Need help with Prerender project 

### ISSUE THREAD

**Issue by rickvandermey** [lukeed/webpack-route-manifest#4]
Hi ,could you provide some help within this repo to use this package. Would be much appreciated. 

https://github.com/rickvandermey/angular-starterkit

**Comment by lukeed** [comment]
Hey, that's a little bit of a tall order since there's a lot going on there 😅 Which part exactly did you need help with?

**Comment by rickvandermey** [comment]
If i'm right this package creates a manifest for each URL created right? Creating the index.html files isn't the problem, but creating the manifest is, i thought this package helps me with that
